// PROPERTY OF THE OWNER. PRIVATE CORPUS.
// SUBJECT TO UNIVERSAL NON-CIRCUMVENTION.
// NO UNAUTHORIZED ACCESS OR AI TRAINING PERMITTED.

use std::collections::HashMap;
use std::fmt;

use super::sensor::SensoryModality;
use super::scene::Scene;
use crate::RealityError;

/// ObservationSource: The origin of an observation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ObservationSource {
    /// Direct sensory input from the environment.
    Direct,
    /// Inferred from other observations via reasoning.
    Inferred,
    /// Recalled from memory.
    Memory,
    /// Generated by a predictive model.
    Modeled,
    /// Reported by another agent or system.
    Reported,
    /// Hypothesized or guessed.
    Hypothesized,
}

impl ObservationSource {
    /// Returns the string label of this source.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Direct => "direct",
            Self::Inferred => "inferred",
            Self::Memory => "memory",
            Self::Modeled => "modeled",
            Self::Reported => "reported",
            Self::Hypothesized => "hypothesized",
        }
    }

    /// Returns the base reliability weight for this source type.
    pub fn base_reliability(&self) -> f64 {
        match self {
            Self::Direct => 0.95,
            Self::Inferred => 0.80,
            Self::Memory => 0.70,
            Self::Modeled => 0.65,
            Self::Reported => 0.60,
            Self::Hypothesized => 0.30,
        }
    }

    /// Returns whether this source requires validation.
    pub fn requires_validation(&self) -> bool {
        matches!(self, Self::Inferred | Self::Modeled | Self::Reported | Self::Hypothesized)
    }

    /// Returns whether this source is primary (direct or memory).
    pub fn is_primary(&self) -> bool {
        matches!(self, Self::Direct | Self::Memory)
    }
}

impl std::fmt::Display for ObservationSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl Default for ObservationSource {
    fn default() -> Self {
        Self::Direct
    }
}

/// ObservationConfidence: The confidence level of an observation.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd)]
pub struct ObservationConfidence(pub f64);

impl ObservationConfidence {
    /// Minimum valid confidence value.
    pub const MIN: f64 = 0.0;
    /// Maximum valid confidence value.
    pub const MAX: f64 = 1.0;
    /// Threshold below which observations are considered uncertain.
    pub const UNCERTAIN_THRESHOLD: f64 = 0.3;
    /// Threshold above which observations are considered reliable.
    pub const RELIABLE_THRESHOLD: f64 = 0.7;

    /// Creates a new observation confidence.
    ///
    /// # Errors
    /// Returns `RealityError::OutOfRange` if value is outside [0.0, 1.0].
    pub fn new(value: f64) -> Result<Self, RealityError> {
        if value.is_nan() || value.is_infinite() {
            return Err(RealityError::InvalidMeasurement {
                value,
                reason: "confidence must be finite".to_string(),
            });
        }
        if value < Self::MIN || value > Self::MAX {
            return Err(RealityError::OutOfRange {
                field: "confidence".to_string(),
                value,
                min: Self::MIN,
                max: Self::MAX,
            });
        }
        Ok(Self(value.clamp(Self::MIN, Self::MAX)))
    }

    /// Returns whether this confidence is below the uncertain threshold.
    pub fn is_uncertain(&self) -> bool {
        self.0 < Self::UNCERTAIN_THRESHOLD
    }

    /// Returns whether this confidence is above the reliable threshold.
    pub fn is_reliable(&self) -> bool {
        self.0 >= Self::RELIABLE_THRESHOLD
    }

    /// Returns whether this confidence is in a moderate range.
    pub fn is_moderate(&self) -> bool {
        !self.is_uncertain() && !self.is_reliable()
    }

    /// Blends two confidence values with a weight.
    pub fn blend(&self, other: &Self, weight: f64) -> Result<Self, RealityError> {
        let w = weight.clamp(0.0, 1.0);
        let blended = self.0 * w + other.0 * (1.0 - w);
        Self::new(blended)
    }

    /// Returns the inverse confidence (uncertainty).
    pub fn uncertainty(&self) -> Self {
        Self(1.0 - self.0)
    }
}

impl Default for ObservationConfidence {
    fn default() -> Self {
        Self(0.5)
    }
}

impl std::fmt::Display for ObservationConfidence {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:.2}", self.0)
    }
}

/// Observation: A single unit of perceived reality.
///
/// Observations are the atomic units of the reality interface. Each observation
/// carries a timestamp, source information, confidence level, and structured data.
#[derive(Debug, Clone, PartialEq)]
pub struct Observation {
    /// Unique identifier for this observation.
    pub id: String,
    /// Timestamp when the observation was recorded.
    pub timestamp: f64,
    /// Source of the observation.
    pub source: ObservationSource,
    /// Sensory modality through which this was observed.
    pub modality: SensoryModality,
    /// Confidence in the observation's accuracy.
    pub confidence: ObservationConfidence,
    /// Structured data payload.
    pub data: HashMap<String, String>,
    /// Free-form description.
    pub description: String,
    /// Optional scene context.
    pub scene: Option<Scene>,
}

impl Observation {
    /// Minimum valid timestamp (Unix epoch).
    pub const MIN_TIMESTAMP: f64 = 0.0;
    /// Maximum valid timestamp (year 3000 in seconds).
    pub const MAX_TIMESTAMP: f64 = 32503680000.0;

    /// Creates a new observation.
    ///
    /// # Errors
    /// Returns `RealityError::OutOfRange` if timestamp is outside valid range.
    pub fn new(
        id: impl Into<String>,
        timestamp: f64,
        source: ObservationSource,
        modality: SensoryModality,
        description: impl Into<String>,
    ) -> Result<Self, RealityError> {
        if timestamp < Self::MIN_TIMESTAMP || timestamp > Self::MAX_TIMESTAMP {
            return Err(RealityError::OutOfRange {
                field: "timestamp".to_string(),
                value: timestamp,
                min: Self::MIN_TIMESTAMP,
                max: Self::MAX_TIMESTAMP,
            });
        }
        Ok(Self {
            id: id.into(),
            timestamp,
            source,
            modality,
            confidence: ObservationConfidence::default(),
            data: HashMap::new(),
            description: description.into(),
            scene: None,
        })
    }

    /// Sets the confidence of this observation.
    pub fn with_confidence(mut self, confidence: ObservationConfidence) -> Self {
        self.confidence = confidence;
        self
    }

    /// Adds a data attribute to the observation.
    pub fn with_data(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.data.insert(key.into(), value.into());
        self
    }

    /// Sets the scene context for this observation.
    pub fn with_scene(mut self, scene: Scene) -> Self {
        self.scene = Some(scene);
        self
    }

    /// Returns the age of this observation in the given time units.
    pub fn age(&self, now: f64) -> f64 {
        now - self.timestamp
    }

    /// Returns whether this observation is stale relative to a maximum age.
    pub fn is_stale(&self, now: f64, max_age: f64) -> bool {
        self.age(now) > max_age
    }

    /// Returns whether this observation requires validation.
    pub fn requires_validation(&self) -> bool {
        self.source.requires_validation() || self.confidence.is_uncertain()
    }

    /// Computes a quality score combining source reliability and confidence.
    pub fn quality_score(&self) -> f64 {
        let source_weight = self.source.base_reliability();
        let confidence_weight = self.confidence.0;
        (source_weight + confidence_weight) / 2.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn observation_creation_succeeds() {
        let obs = Observation::new(
            "obs-1",
            1000.0,
            ObservationSource::Direct,
            SensoryModality::Visual,
            "a red sphere on a table",
        )
        .unwrap();
        assert_eq!(obs.id, "obs-1");
        assert_eq!(obs.timestamp, 1000.0);
        assert_eq!(obs.modality, SensoryModality::Visual);
    }

    #[test]
    fn observation_rejects_invalid_timestamp() {
        let result = Observation::new(
            "obs-bad",
            -1.0,
            ObservationSource::Direct,
            SensoryModality::Visual,
            "bad timestamp",
        );
        assert!(result.is_err());
    }

    #[test]
    fn confidence_blending_works() {
        let c1 = ObservationConfidence::new(0.8).unwrap();
        let c2 = ObservationConfidence::new(0.4).unwrap();
        let blended = c1.blend(&c2, 0.5).unwrap();
        assert!((blended.0 - 0.6).abs() < 1e-10);
    }

    #[test]
    fn observation_quality_score() {
        let obs = Observation::new(
            "obs-q",
            1000.0,
            ObservationSource::Direct,
            SensoryModality::Visual,
            "quality test",
        )
        .unwrap()
        .with_confidence(ObservationConfidence::new(0.9).unwrap());
        let score = obs.quality_score();
        assert!((score - 0.925).abs() < 1e-10);
    }

    #[test]
    fn observation_requires_validation_for_hypothesized() {
        let obs = Observation::new(
            "obs-hyp",
            1000.0,
            ObservationSource::Hypothesized,
            SensoryModality::Abstract,
            "hypothesis",
        )
        .unwrap();
        assert!(obs.requires_validation());
    }
}

